### ISSUE TITLE
Self host error on vercel and cf pages.

### ISSUE THREAD

**Issue by heyjumanji** [MediaSavvy/MediaSavvy_Wiki#7]
How to self host.

**Comment by MediaSavvy** [comment]
Hey! Here's how to self host MediaSavvy on Cloudflare Pages:

Before we continue make sure you have Git installed on your system which is logged into your GitHub account. Also make sure that you have already linked a GitHub repository with no files in it to Cloudflare Pages. 
 
1. Go to the MediaSavvy_Wiki repository and click the green "Code" button and click "Download ZIP".
2. Extract the ZIP file.
3. Open Command Prompt and go to the extracted folder using the command: cd c:/users/-user-/downloads/MediaSavvy_Wiki-main/MediaSavvy_Wiki-main. Replace "-user-" with your Windows username.
4. Now again in Command Prompt type "git init".
5. For simplicity we are going to be using Git GUI for the next few steps which should have been installed while installing Git. Open Git GUI and go to the extracted folder from earlier.
6. Once in Git GUI, on top off the application you'll see a option called "Branch". Click that and then click "Rename" and change the name from master to main.
7. Now click "Stage Changed". If a new window popped up that says "Updating the Git index failed. A rescan will be automatically started to resynchronize git-gui." then click "Continue".
8. After write any message in the box that says "Commit Message".
9. Then click "Commit".
10. After click "Push" and then click "Arbitrary Location" and enter the URL of the GitHub repository that is linked to Cloudflare Pages.

Now wait a few minutes for Cloudflare to deploy and you should be up and running! Let me know how it goes and if you need additional help please reply!
